export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_LIBRARY = 'GET_LIBRARY';
export const LIBRARY_LOADING = 'LIBRARY_LOADING';
export const CLEAR_CURRENT_LIBRARY = 'CLEAR_CURRENT_LIBRARY';
